# Generated by Django 4.1 on 2022-08-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='توضیحات')),
                ('created', models.DateTimeField(verbose_name='زمان ساخت')),
            ],
            options={
                'verbose_name': 'کار',
                'verbose_name_plural': 'لیست کار ها',
                'db_table': 'todo',
                'ordering': ('-created',),
            },
        ),
    ]
